### ISSUE TITLE
1.18.1 tome not changing to book

### ISSUE THREAD

**Issue by Tomatoh** [Vazkii/AkashicTome#83] opened 2022-02-10 13:31 UTC
1.18.1 version AkashicTome-1.5-17.jar can add books but not change to them by right click > open menu > right click change to book

**Comment by Slickson77** [comment] 2022-02-11 03:21
I agree ... doesn't seem to work

**Comment by Dutchs** [comment] 2022-02-13 14:44
It throws this in the console when you try:
```
[Server thread/FATAL]: Error executing task on Server
java.lang.RuntimeException: java.lang.NoSuchMethodException: vazkii.akashictome.network.MessageMorphTome.<init>()
	at vazkii.arl.network.NetworkHandler.lambda$register$1(NetworkHandler.java:55) ~[AutoRegLib-1.7-53.jar%2353!/:1.7-53]
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:120) ~[forge-1.18.1-39.0.66-universal.jar%2368!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:120) ~[forge-1.18.1-39.0.66-universal.jar%2368!/:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge-1.18.1-39.0.66-universal.jar%2368!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:82) ~[forge-1.18.1-39.0.66-universal.jar%2368!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%2337!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%2337!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2337!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2337!/:?]
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:82) ~[forge-1.18.1-39.0.66-universal.jar%2368!/:?]
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:89) ~[forge-1.18.1-39.0.66-universal.jar%2368!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:89) ~[forge-1.18.1-39.0.66-universal.jar%2368!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:1416) ~[client-1.18.1-20211210.034407-srg.jar%2364!/:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[client-1.18.1-20211210.034407-srg.jar%2364!/:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[client-1.18.1-20211210.034407-srg.jar%2364!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[client-1.18.1-20211210.034407-srg.jar%2364!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.1-20211210.034407-srg.jar%2364!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[client-1.18.1-20211210.034407-srg.jar%2364!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%2364!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[client-1.18.1-20211210.034407-srg.jar%2364!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.18.1-20211210.034407-srg.jar%2364!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[client-1.18.1-20211210.034407-srg.jar%2364!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[client-1.18.1-20211210.034407-srg.jar%2364!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[client-1.18.1-20211210.034407-srg.jar%2364!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[client-1.18.1-20211210.034407-srg.jar%2364!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[client-1.18.1-20211210.034407-srg.jar%2364!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[client-1.18.1-20211210.034407-srg.jar%2364!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2364!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodException: vazkii.akashictome.network.MessageMorphTome.<init>()
	at java.lang.Class.getConstructor0(Class.java:3585) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?]
	at vazkii.arl.network.NetworkHandler.lambda$register$1(NetworkHandler.java:51) ~[AutoRegLib-1.7-53.jar%2353!/:1.7-53]
	... 30 more
```

**Comment by faeandsugar** [comment] 2022-02-24 04:51
Same issue for me. I hope this gets addressed soon.

**Comment by CyaniideDrive** [comment] 2022-02-25 00:00
Guess this is the same for a lot of people, I got this too.
Really sucks because it ate a fully complete Silent Gear Blueprint Book.

**Comment by jupiter-august** [comment] 2022-02-28 06:38
It's so odd, because it seemed to have worked at first. Just to clarify, it lets us craft the book, and it opens to the selection choices, but when we try to select one, the menu disappears as if we had backed out of it, and the book does not change.

An amazing mod! I hope this is fixed soon!

**Comment by nonatee** [comment] 2022-03-03 11:13
have the same problem

**Comment by Mystara0001** [comment] 2022-03-12 18:50
I was wondering if there was a beta or hotfix for this as this is a mod breaking bug.

**Comment by AndrewSatterfield** [comment] 2022-03-20 09:15
Getting this issue as well

**Comment by EccentricVamp** [comment] 2022-03-24 02:39
I don't think this bug will get fixed until Minecraft 1.19 comes out and someone from the @Vazkii team comes back in to update this mod.

The bug is caused by an error in communication between Akashic Tome and its utility library, [AutoRegLib](https://www.curseforge.com/minecraft/mc-mods/autoreglib).

Thanks to the error log @Dutchs provided above, I was able to fix this issue in the code in just a few minutes (the fix is literally two lines of code). I opened a [pull request to fix it](https://github.com/VazkiiMods/AkashicTome/pull/85), but its been 24 days and I still haven't gotten a response.

If you're interested in a mod that provides identical functionality, I made a new mod that does the same things as this one and it doesn't depend on AutoRegLib.

https://curseforge.com/minecraft/mc-mods/eccentric-tome

https://github.com/EccentricVamp/EccentricTome

**Comment by Vazkii** [comment] 2022-03-24 03:36
Hi @EccentricVamp thanks for tagging me here. One of us though the other had this repo in check and the other thought the other did, whereas in reality no one did and it was just sitting there. We should be getting a fix out shortly.

**Comment by EccentricVamp** [comment] 2022-03-24 13:22
Thanks @Vazkii! I also tagged @Alwinfy (the person who updated it to 1.18.1) in the pull request that I opened a while ago, but they never responded. @Alwinfy must be busy with other things since they also didn't do any in-game testing when they updated and published this mod.

I use this mod quite a bit and I maintain software for a living, so let me know if you need any extra maintainers for this repo. I'd be happy to help.

**Comment by ZEROX7** [comment] 2022-03-24 19:43
version 1.5-18 still doesnt work im not a coder so idk if waht @Alwinfy did was even supposed to fix the issue idk

**Comment by Vazkii** [comment] 2022-03-24 22:03
Should be fixed in 19 hopefully

**Closed as completed** 2024-08-17 16:42 UTC
